### ISSUE TITLE
Move `bitflags` out of the nursery?

### ISSUE THREAD

**Issue by KodrAus** [rust-lang-nursery/ecosystem-wg#2]
The [`bitflags`](https://github.com/rust-lang-nursery/bitflags) crate is now stable and the nursery doesn't seem like the most appropriate home for it anymore.

Would we like to find the crate a new home under a GitHub organisation in the community?

**Comment by steveklabnik** [comment]
Traditionally, and according to the RFCs, moving it to rust-lang-deprecated is the process here, and then someone can claim it.

Of course, if someone wants to claim it, moving it straight to them seems good!

**Comment by KodrAus** [comment]
That's true! We ended up moving `uuid` straight into a GitHub organisation with everyone that expressed any interest in it and that seems to have gone well. I'm wondering if putting `bitflags` in the `rust-lang-deprecated` organisation first might send the wrong kind of message? We don't want to deprecate the crate. It's actually the total opposite! We want the crate to get more dedicated attention. Maybe that's just semantics though :)

**Comment by aturon** [comment]
Yeah I don't think we should go through deprecation. I think the rust-lang policy RFC is highly outdated at this point.

**Comment by Dylan-DPC** [comment]
Hey. I can create the organisation when needed. Just give me a ping :)

**Comment by KodrAus** [comment]
Thanks @Dylan-DPC! Let's give folks a chance to express interest and then coordinate setting up an org with them all like we did for `uuid`.

**Comment by Dylan-DPC** [comment]
@KodrAus sure. We need to make a post calling for co-maintainers. That will help move things faster

**Comment by KodrAus** [comment]
@Dylan-DPC Good point! The ecosystem post was meant to be that call, but I've [put something more specific on the users discourse](https://users.rust-lang.org/t/help-maintain-bitflags/17710) too.

**Comment by Dylan-DPC** [comment]
@IsaacWoods sounds good. Will send you an invite when we create the organisation

**Comment by KodrAus** [comment]
Also cc @djg are you still interested in `bitflags`?

**Comment by djg** [comment]
I'm happy to contribute if I can. What do you have in mind @KodrAus?

**Comment by KodrAus** [comment]
@djg that depends on what you'd like to do :) Having write access means you could also jump in and help triage/close issues, review/merge PRs, publish new versions to `crates.io`. There's also new features to consider, like your current iterator API, and over time new idioms in the language that we might want to incorporate somehow. Who knows what the future holds!

**Comment by Dylan-DPC-zz** [comment]
yeah to add to what Ashley said, you can check dependent crates and send them PRs to update to the latest version of bitflags when we release one

**Comment by Dylan-DPC-zz** [comment]
Have created an [organisation](https://github.com/bitflags) and sent invites. If anyone else is interested in joining, leave a message here.

**Comment by djg** [comment]
@KodrAus I still don't have a good solution to the iterator API!

**Comment by kinggoesgaming** [comment]
would this be considered resolved as `bitflags` has been moved?

**Comment by Dylan-DPC-zz** [comment]
@kinggoesgaming i wanted to keep this issue open for a few days in case anyone else is interested in jumping in as a co-maintainer.

**Comment by KodrAus** [comment]
I think enough time's passed now that we can close this one. Thanks to everyone who's stepped up to support `bitflags`!
